language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
  - npm
branches:
  only:
  - master
install:
- npm install
script:
- git config user.name "wenfs"
- git config user.email "wefashe@qq.com"
- npm run deploy
before_install:
- openssl aes-256-cbc -K $encrypted_e34fefeac313_key -iv $encrypted_e34fefeac313_iv
  -in id_rsa.enc -out id_rsa -d
