language: node_js

node_js:
- node

cache:
  directories:
  - node_modules

# master为hexo博客所在分支
branches:
  only:
  - master

# before_install:
#   - openssl aes-256-cbc -K $encrypted_e34fefeac313_key -iv $encrypted_e34fefeac313_iv -in id_rsa.enc -out id_rsa -d

  # 改变文件权限
#   - chmod 600 ~/.ssh/id_rsa

  # 配置 ssh
#   - eval $(ssh-agent)
#   - ssh-add ~/.ssh/id_rsa
#   - cp .travis/ssh_config ~/.ssh/config

install:
  - npm install

script:
#   - npm run deploy
  - npm run build


after_script:
  - cd ./dist
  - git init
  - git config user.name "wenfs"
  - git config user.email "wefashe@qq.com"
  - git add -A
  - git commit -m "deploy :construction:"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages


env:
 global:
   - GH_REF: github.com/wefashe/wenfsblog.git
