language: node_js
# sudo: required
node_js:
    -8.9.3
cache:
  directories:
    - node_modules
branches:
  only:
    -master

# before_install:
#   - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install
#   - npm install hexo-deployer-git --save

script:
#   - hexo clean
#   - hexo generate
  - git config user.name "wenfs"
    - git config user.email "wefashe@qq.com"
    - npm run deploy

# after_script:
#     - git config user.name "wenfs"
#     - git config user.email "wefashe@qq.com"
#     - npm run deploy
