language: node_js

node_js: node

cache:
  directories:
  - node_modules

# master为hexo博客所在分支
branches:
  only:
  - master

before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - chmod +x ./build/deploy.sh  # 为shell文件添加可执行权限

install:
  - npm install

script:
  - ./build/deploy.sh
#   - npm run deploy


after_script:
  - echo 'Build completed!'

#设置变量GH_REF
env:
 global:
   - GH_REF: github.com/wefashe/wenfsblog.git
